### ISSUE TITLE
ValueError: bad marshal data (unknown type code)

### ISSUE THREAD

**Issue by cosmolu** [chaitanya100100/VAE#4]
I use keras =2.2.2, tf=1.8.0gpu, python=3.6
run the mnist_general_latent_space_and_generate.py
Is that because of the version do not match? 
I am a beginner, thank you so much!

Then the error:

> /home/cosmo/anaconda3/envs/tf8/bin/python /home/cosmo/PycharmProjects/insider_attack/vae/VAE-for-Image-Generation/src/mnist_general_latent_space_and_generate.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/cosmo/anaconda3/envs/tf8/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 230, in func_load
    raw_code = codecs.decode(code.encode('ascii'), 'base64')
UnicodeEncodeError: 'ascii' codec can't encode character '\x83' in position 52: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cosmo/PycharmProjects/insider_attack/vae/VAE-for-Image-Generation/src/mnist_general_latent_space_and_generate.py", line 49, in <module>
    custom_objects={'latent_dim':latent_dim, 'epsilon_std':epsilon_std, 'CustomVariationalLayer':CustomVariationalLayer})
  File "/home/cosmo/anaconda3/envs/tf8/lib/python3.6/site-packages/keras/engine/saving.py", line 260, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/home/cosmo/anaconda3/envs/tf8/lib/python3.6/site-packages/keras/engine/saving.py", line 334, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/home/cosmo/anaconda3/envs/tf8/lib/python3.6/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/home/cosmo/anaconda3/envs/tf8/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/cosmo/anaconda3/envs/tf8/lib/python3.6/site-packages/keras/engine/network.py", line 1017, in from_config
    process_layer(layer_data)
  File "/home/cosmo/anaconda3/envs/tf8/lib/python3.6/site-packages/keras/engine/network.py", line 1003, in process_layer
    custom_objects=custom_objects)
  File "/home/cosmo/anaconda3/envs/tf8/lib/python3.6/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/home/cosmo/anaconda3/envs/tf8/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/cosmo/anaconda3/envs/tf8/lib/python3.6/site-packages/keras/layers/core.py", line 730, in from_config
    function = func_load(config['function'], globs=globs)
  File "/home/cosmo/anaconda3/envs/tf8/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 235, in func_load
    code = marshal.loads(raw_code)
ValueError: bad marshal data (unknown type code)

Process finished with exit code 1

**Comment by chaitanya100100** [comment]
Looking at [This](https://stackoverflow.com/questions/9942594/unicodeencodeerror-ascii-codec-cant-encode-character-u-xa0-in-position-20) thread, it seems to be the python version problem.
